pattern = 'v0.2.%d'
types = ["Cargo"]
message-template = "Created {version} for release."

[artifact.mac]
paths = {inc = "artifacts/inc-mac/inc"}
compress = { name = "inc-mac.tar.gz", format = "tgz" }
target = "GitHub"

[artifact.linux]
paths = {inc = "artifacts/inc-linux/inc"}
compress = { name = "inc-linux-musl.tar.gz", format = "tgz" }
target = "GitHub"
