[exec]
ci = { commands = [
    "env",
    "cargo build",
    "cargo test"
 ] }
release = { commands = [ 
    "cargo build --release",
    "cargo build --target=x86_64-apple-darwin --release",
    "cargo build --target=x86_64-pc-windows-gnu --release"
] }

[exec.build]
commands = "cargo build"
description = "Run a normal debug build"