[package]
name = "inc-bin"
version = ""0.1.1""
authors = ["Ethan Hall <ethan@ehdev.io>"]

[dependencies]
inc-core = { version = ""0.1.1"" }
docopt = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"

[dev-dependencies]
assert_cli = "0.5"
tempdir = "0.3"
toml = "0.4"
serde = "1.0.15"
serde_derive = "1.0.15"

[[bin]]
name = "inc"
test = false
doc = false
