version: 2
jobs:
  build:
    docker:
      - image: ethankhall/rust-cross-build:latest
    steps:
      - run:
          name: Pull artifacts
          command: |
            curl --location https://github.com/ethankhall/release-manager/releases/download/v0.1.10/release-manager-linux -o ~/release-manager
            chmod +x ~/release-manager
      - run:
          name: Update Rust
          command: rustup update
      - run:
          name: Update System Cache
          command: yaourt -Sy
      - run:
          name: Install SSH
          command: yaourt -S --noconfirm openssh jq
      - checkout
      - run:
          name: Build Initial Inc Binary
          command: cargo build
      - run:
          name: Make a copy of inc
          command: cp ./target/debug/inc ~/inc
      - run:
          name: Build with inc.
          command: ~/inc exec ci
      - run:
          name: Build All Variants
          command: ~/inc exec release
      - run:
          name: Tag Version
          command: |
            ~/release-manager github release-and-bump
            ~/release-manager github artifacts inc-windows.exe=target/x86_64-pc-windows-gnu/release/inc.exe inc-mac=target/x86_64-apple-darwin/release/inc inc-linux=target/release/inc

