[package]
name = "etrain-checkout"
version = "0.1.0"
authors = ["Ethan Hall <ethan@ehdev.io>"]

[dependencies]
etrain-core = { version = "0.1.0", path = "../../lib/core" }
etrain-checkout-lib = { version = "0.1.0", path = "../../lib/checkout" }
slog = { version = "2", features = ["max_level_trace", "release_max_level_trace"] }