[package]
name = "etrain"
version = "0.1.0"
authors = ["Ethan Hall <ethan@ehdev.io>"]

[dependencies]
etrain-core = { version = "0.1.0", path = "../../lib/core" }
etrain-main-entrypoint-lib = { version = "0.1.0", path = "../../lib/main-entrypoint" }